# Generated by Django 4.0.1 on 2022-02-16 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_logs', '0005_topic_public'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('text', 'owner')},
        ),
    ]
